#ifndef KEYBOARD_H
#define KEYBOARD_H

int  getkey (char *ascii);

/* Scan codes */
#define KB_P                   25   /* "P" */
#define KB_ESC                 1
#define KB_BACKSPACE           14
#define KB_TAB                 15
#define KB_RETURN              28
#define KB_UP                  72
#define KB_LEFT                75
#define KB_RIGHT               77
#define KB_DOWN                80
#define KB_PERIOD              52
#define KB_COMMA               51
#define KB_SPACE               57
#define KB_PGDN                81
#define KB_PGUP                73

#endif /* KEYBOARD_H */
